### ISSUE TITLE
Order Component

### ISSUE THREAD

**Issue by Longshoez** [BC-MAY-21-RN/proyecto-final-pf-n21-t4#52]
# Requirement 

# Design
![image](https://user-images.githubusercontent.com/26613957/156463210-a3f74a87-1cbe-4b60-9bd3-ab7a57efd2f2.png)

# Acceptance criteria
- [x] Order Component
  - [x] Order Code
  - [x] Client Name
  - [x] Client address
  - [x] Order items
  - [x] Total Order Cost

- [x] Order Component functionality
  - [x] Loads actual user data
  - [x] Loads the actual order items
  - [x] Calculates the total order cost

- [x] Call Client Button
- [x] Order Options (Modal)
  - [x] Cancel Order
  - [x] Complete Order

**Comment by Longshoez** [comment]
Los checkboxes se van a eliminar para el mvp, no presentan una funcion muy necesaria por el momento.

**Comment by Javier-Barreto** [comment]
It doesn't cancel the order at all, we need to still cancel the order in the user collection in firebase.
